#!/bin/sh

HERMITUX_BASE=/home/pierre/hermitux
HERMIT_LOCAL_INSTALL=$HERMITUX_BASE/hermit-compiler/prefix
KERNEL=$HERMIT_LOCAL_INSTALL/x86_64-hermit/extra/tests/hermitux

VERBOSE=1

HERMIT_VERBOSE=$VERBOSE HERMIT_ISLE=uhyve HERMIT_TUX=1 \
				$HERMIT_LOCAL_INSTALL/bin/proxy $KERNEL \
				$@

