#!/bin/sh

# Use this script for quick and easy run of a linux binary as a unikernel

# Set this variable to hermitux codebase directory
HERMITUX_BASE=$HOME/git/hermitux
HERMIT_LOCAL_INSTALL=$HERMITUX_BASE/hermitux-kernel/prefix

KERNEL=$HERMIT_LOCAL_INSTALL/x86_64-hermit/extra/tests/hermitux
VERBOSE=1

HERMIT_VERBOSE=$VERBOSE HERMIT_ISLE=uhyve HERMIT_TUX=1 \
				$HERMIT_LOCAL_INSTALL/bin/proxy $KERNEL \
				$@

